### ISSUE TITLE
Adjust Technology Tree Formspec

### ISSUE THREAD

**Issue by Jeija** [CERN/CTW#31]
The current tech tree formspec display is broken:

![Tech tree screenshot](https://user-images.githubusercontent.com/1311964/64981329-1e945680-d8bc-11e9-8502-4a162184733d.png)

The formspec should be adjusted to be able to deal with the larger size of the actual in-game tech tree compared to the tech tree that was used for testing / developing the formspec. The formspec should also take technology eras into account.

**Comment by orwell96** [comment]
I think we should just resort on positioning elements manually
I can handle this next week
